// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFpgKb9EqpLSDxHSNj5Gqn-Q3iewnkRUY',
    appId: '1:524506788721:web:280c2a5baf20fcfba83cd0',
    messagingSenderId: '524506788721',
    projectId: 'ecommerce-dbece',
    authDomain: 'ecommerce-dbece.firebaseapp.com',
    storageBucket: 'ecommerce-dbece.appspot.com',
    measurementId: 'G-BMQYNB3K0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdhR9CAh3ezsE9Q4AaFBOknFNtbJhQqrs',
    appId: '1:524506788721:android:3501151e370854eda83cd0',
    messagingSenderId: '524506788721',
    projectId: 'ecommerce-dbece',
    storageBucket: 'ecommerce-dbece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmiLfyp2glk8ChWCAQDD8KjpNWjJSUP1c',
    appId: '1:524506788721:ios:ee69b35a78b3187fa83cd0',
    messagingSenderId: '524506788721',
    projectId: 'ecommerce-dbece',
    storageBucket: 'ecommerce-dbece.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmiLfyp2glk8ChWCAQDD8KjpNWjJSUP1c',
    appId: '1:524506788721:ios:ee69b35a78b3187fa83cd0',
    messagingSenderId: '524506788721',
    projectId: 'ecommerce-dbece',
    storageBucket: 'ecommerce-dbece.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFpgKb9EqpLSDxHSNj5Gqn-Q3iewnkRUY',
    appId: '1:524506788721:web:84d17a08a5e1e840a83cd0',
    messagingSenderId: '524506788721',
    projectId: 'ecommerce-dbece',
    authDomain: 'ecommerce-dbece.firebaseapp.com',
    storageBucket: 'ecommerce-dbece.appspot.com',
    measurementId: 'G-X4S04W56C9',
  );
}
